### ISSUE TITLE
Machine Provider | Azure | Support Premium SSD

### ISSUE THREAD

**Issue by solesensei** [loft-sh/devpod-provider-azure#2]
Is your feature request related to a problem?

Right now you can't control VM disk type with devpod. For e.g. you can't select PremiumSSD, by default devpod creates VM with HDD.

Which solution do you suggest?

Add possibility to choose disk type.

Which alternative solutions exist?

Additional context

related https://github.com/loft-sh/devpod/issues/732

**Comment by 89luca89** [comment]
Thanks for the issue @solesensei we'll take a look :+1: 

Or if you've already thought of a solution, feel free to open a PR :)
