### ISSUE TITLE
Support cloud-init

### ISSUE THREAD

**Issue by solesensei** [loft-sh/devpod-provider-azure#8]
Right now I'm using `az cli` to create my Azure VM, [script](https://gist.github.com/solesensei/05de2460d0d85e8ddcc173d2d1d49d31#file-create-vm-sh) and devpod SSH provider to create containers.

For me it's important to have `--custom-data vm-init.sh` argument to pass initialisation script for created Virtual Machine.

It would be nice to have that option `path/to/vm-init/script.sh` in the Azure provider itself.

**Comment by pascalbreuninger** [comment]
Hi @solesensei, could you contribute this to the provider? [This guide](https://devpod.sh/docs/developing-providers/options) is a good place to get started for adding an option
